#!/usr/bin/env bash
# shellcheck disable=SC2094,SC2210,SC3028,SC2211,SC2171,SC2288,SC2238
# Shellchecks disabled for this file
# SC2094: Make sure not to read and write the same file in the same pipeline.
# SC2171: Found trailing ] outside test. Add missing [ or quote if intentional.
# SC2210: This is a file redirection. Was it supposed to be a comparison or fd operation?
# SC2211: This is a glob used as a command name. Was it supposed to be in ${..}, array, or is it missing quoting?
# SC2238: Redirecting to/from command name instead of file. Did you want pipes/xargs (or quote to ignore)?
# SC2288: This is interpreted as a command name ending with apostrophe. Double check syntax.
# SC3028: In POSIX sh, VARIABLE is undefined.

############################# Mode definitions ##################################
:: default           : ~/.config/skhd/mode_controller.sh default # default mode: normal
:: stack   @         : ~/.config/skhd/mode_controller.sh stack # stack mode: interact with stacks
:: display @         : ~/.config/skhd/mode_controller.sh display # display mode: focus displays, move windows to other displays
:: window  @         : ~/.config/skhd/mode_controller.sh window # window mode: manipulate windows and spaces
:: resize  @         : ~/.config/skhd/mode_controller.sh resize # resize mode: resize windows in current space
:: inst    @         : ~/.config/skhd/mode_controller.sh inst # insert mode: tell yabai where to insert the new window

# Hack to use "ctrl + shift - r" keybinding in RubyMine
# to run tests but trigger resize mode everywhere else
# meh is (shift + alt + ctrl)
default < ctrl + shift - r [
  "rubymine"   ~
  "rubymine-eap"   ~
  "code"   ~
  "cursor"   ~
  "windsurf"   ~
  * : skhd -k "meh - r"
]

resize < ctrl + shift - r [
  "rubymine"   ~
  "rubymine-eap"   ~
  "code"   ~
  "cursor"   ~
  "windsurf"   ~
  * : skhd -k "meh - r"
]

# Override display mode
default < ctrl + shift - d [
  "rubymine"   ~
  "rubymine-eap"   ~
  "code"   ~
  "cursor"   ~
  "windsurf"   ~
  * : skhd -k "meh - d"
]

resize < ctrl + shift - d [
  "rubymine"   ~
  "rubymine-eap"   ~
  "code"   ~
  "cursor"   ~
  "windsurf"   ~
  * : skhd -k "meh - d"
]

# Activate modes from default
default < meh - d          ; display
default < ctrl + shift - s ; stack
default < ctrl + shift - w ; window
default < meh - r          ; resize
default < ctrl + shift - i ; inst

# Exit any mode and return to default
display, window, resize, stack, inst < escape ; default
display < meh - d          ; default
stack   < ctrl + shift - s ; default
window  < ctrl + shift - w ; default
resize  < meh - r          ; default
inst    < ctrl + shift - i ; default

# Hop directly between non-default modes via single-letter keys
stack, window, resize, inst    < d ; display
display, window, resize, inst  < s ; stack
display, stack, resize, inst   < w ; window
display, stack, window, inst   < r ; resize
display, stack, window, resize < i ; inst

############################# Help popup ########################################
# Show keybinding help for the current mode using sketchybar
# (see ~/.config/sketchybar/plugins/help/). 0x2C is the keycode for `/`
default < ctrl + shift - 0x2C : ~/.config/sketchybar/plugins/help/toggle_help.sh default
stack   < shift - 0x2C        : ~/.config/sketchybar/plugins/help/toggle_help.sh stack
display < shift - 0x2C        : ~/.config/sketchybar/plugins/help/toggle_help.sh display
window  < shift - 0x2C        : ~/.config/sketchybar/plugins/help/toggle_help.sh window
resize  < shift - 0x2C        : ~/.config/sketchybar/plugins/help/toggle_help.sh resize
inst    < shift - 0x2C        : ~/.config/sketchybar/plugins/help/toggle_help.sh inst

############################# Global modifiers ##################################
# The aim is to not have too many global key-bindings because it will clash with
# other application based keybindings e.g. VS Code, IntelliJ, etc.

#? Focus prev desktop
ctrl - left            : yabai -m space --focus prev

#? Focus next desktop
ctrl - right           : yabai -m space --focus next

#? Focus recent desktop
ctrl - z               : yabai -m space --focus recent

#? Focus space 1
ctrl - 1               : yabai -m space --focus 1

#? Focus space 2
ctrl - 2               : yabai -m space --focus 2

#? Focus space 3
ctrl - 3               : yabai -m space --focus 3

#? Focus space 4
ctrl - 4               : yabai -m space --focus 4

#? Focus space 5
ctrl - 5               : yabai -m space --focus 5

#? Focus space 6
ctrl - 6               : yabai -m space --focus 6

#? Focus space 7
ctrl - 7               : yabai -m space --focus 7

#? Focus space 8
ctrl - 8               : yabai -m space --focus 8

#? Focus space 9
ctrl - 9               : yabai -m space --focus 9

#? Focus space 10
ctrl - 0               : yabai -m space --focus 10

#? Focus first fullscreen app
ctrl - 0x1B            :  index="$(yabai -m query --spaces --display | \
                                 jq 'map(select(."is-native-fullscreen" == true))[0].index')"; \
                          yabai -m space --focus "$index"

#? Focus second fullscreen app
ctrl - 0x18            :  index="$(yabai -m query --spaces --display | \
                                 jq 'map(select(."is-native-fullscreen" == true))[1].index')"; \
                          yabai -m space --focus "$index"

#? Toggle fullscreen zoom
ctrl + shift - space  : yabai -m window --toggle zoom-fullscreen; \
                        sketchybar --trigger window_focus

#? Focus window right
ctrl + shift - right  : yabai -m window --focus east || \
                        yabai -m window --focus west; \
                        sketchybar --trigger window_focus
#? Focus window left
ctrl + shift - left   : yabai -m window --focus west || \
                        yabai -m window --focus east; \
                        sketchybar --trigger window_focus

# Up/Down actions uses multiple steps to focus window
# First tries to focus the window in `north` direction
# Else, tries to focus the window in `stack.prev` or `stack.last` direction
# Else, tries to focus the first floating window (if any)
# Else, gets the focus back from the `floating` window to the `managed` window

#? Focus window above
ctrl + shift - up     : yabai -m window --focus north || \
                        yabai -m window --focus stack.prev || \
                        yabai -m window --focus stack.last || \
                        yabai -m window --focus "$(yabai -m query --windows --space | jq -r 'map(select(.["has-focus"] == false and .["is-floating"] == true)) | .[0] | .id')" || \
                        yabai -m window --focus "$(yabai -m query --windows --space | jq -r 'map(select(.["has-focus"] == false)) | .[0] | .id')"; \
                        sketchybar --trigger window_focus

#? Focus window below
ctrl + shift - down   : yabai -m window --focus south || \
                        yabai -m window --focus stack.next || \
                        yabai -m window --focus stack.first || \
                        yabai -m window --focus "$(yabai -m query --windows --space | jq -r 'map(select(.["has-focus"] == false and .["is-floating"] == true)) | .[0] | .id')" || \
                        yabai -m window --focus "$(yabai -m query --windows --space | jq -r 'map(select(.["has-focus"] == false)) | .[0] | .id')"; \
                        sketchybar --trigger window_focus

#? Focus window under mouse
ctrl - down           : yabai -m window --focus mouse; \
                        sketchybar --trigger window_focus

# Vi-like aliases for the window-focus arrows above.
ctrl + shift - l      : skhd -k "ctrl + shift - right"
ctrl + shift - h      : skhd -k "ctrl + shift - left"
ctrl + shift - k      : skhd -k "ctrl + shift - up"
ctrl + shift - j      : skhd -k "ctrl + shift - down"

#? Toggle native fullscreen
ctrl + shift - f      : yabai -m window --toggle native-fullscreen

# Fast focus display shortcuts
#? Focus display left
ctrl + alt - left      : yabai -m display --focus west || yabai -m display --focus recent
#? Focus display right
ctrl + alt - right     : yabai -m display --focus east || yabai -m display --focus recent
#? Focus display above
ctrl + alt - up        : yabai -m display --focus north || yabai -m display --focus recent
#? Focus display below
ctrl + alt - down      : yabai -m display --focus south || yabai -m display --focus recent

#? Toggle float + center
alt - f                : yabai -m window --toggle float; \
                         yabai -m window --grid 4:4:1:1:2:2; \
                         sketchybar --trigger window_focus

#? Open Terminal
ctrl + shift - 0x24  : open -na /Applications/Alacritty.app

#? Close focused window
ctrl + shift - q     : yabai -m window --close

# cmd-m here overrides macOS' default minimize-window behaviour.
#? Focus window under mouse
cmd - m              : yabai -m window --focus mouse

######################## Insert mode ###########################################

#? Insert west
inst < left            : yabai -m window --insert west; skhd -k 'escape'
#? Insert south
inst < down            : yabai -m window --insert south; skhd -k 'escape'
#? Insert north
inst < up              : yabai -m window --insert north; skhd -k 'escape'
#? Insert east
inst < right           : yabai -m window --insert east; skhd -k 'escape'
#? Insert as stack
inst < s               : yabai -m window --insert stack; skhd -k 'escape'

######################## Stack mode ############################################

# Stack-with-direction only works when the active window is not already
# part of a stack.
#? Stack with west
stack < left           : yabai -m window west  \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')"; \
                         skhd -k 'escape'

#? Stack with south
stack < down           : yabai -m window south \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')" ; \
                         skhd -k 'escape'

#? Stack with north
stack < up             : yabai -m window north \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')" ; \
                         skhd -k 'escape'

#? Stack with east
stack < right          : yabai -m window east  \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')"; \
                         skhd -k 'escape'

#? Toggle stack/bsp layout
stack < space          : yabai -m query --spaces --space | \
                         jq -re ".type" | \
                         xargs -I {} bash -c \
                         "if [ {} = 'stack' ]; \
                         then yabai -m space --layout bsp; \
                         else yabai -m space --layout stack; \
                         fi"; \
                         skhd -k 'escape'

#? Unstack window
stack < b              : window="$(yabai -m query --windows --window | jq -r '.id')"; \
                         yabai -m window east --stack $window || \
                         (yabai -m window $window --toggle float && yabai -m window $window --toggle float); \
                         skhd -k 'escape'

#? Stack all on current
stack < s              : window="$(yabai -m query --windows --window | jq -r '.id')" && \
                         yabai -m query --windows --space | jq -rc --arg w "$window" '[.[].id] | map(select(. != $w)) | .[]' | \
                         xargs -I {} yabai -m window "$window" --stack {}; \
                         skhd -k 'escape'

####################### Resize mode ############################################

#? Resize left
resize < h             : yabai -m window --resize left:-100:0 || \
                         yabai -m window --resize right:-100:0

#? Resize down
resize < j             : yabai -m window --resize bottom:0:100 || \
                         yabai -m window --resize top:0:100

#? Resize up
resize < k             : yabai -m window --resize top:0:-100 || \
                         yabai -m window --resize bottom:0:-100

#? Resize right
resize < l             : yabai -m window --resize right:100:0 || \
                         yabai -m window --resize left:100:0

# Resize window left using arrow key
resize < left          : skhd -k "h"

# Resize window down using arrow key
resize < down          : skhd -k "j"

# Resize window up using arrow key
resize < up            : skhd -k "k"

# Resize window right using arrow key
resize < right         : skhd -k "l"

#? Balance windows
resize < 0x18          : yabai -m space --balance; skhd -k 'escape'

#? Rotate tree 90°
resize < r             : yabai -m space --rotate 90

#? Mirror y-axis
resize < y             : yabai -m space --mirror y-axis; \
                         skhd -k 'escape'

#? Mirror x-axis
resize < x             : yabai -m space --mirror x-axis; \
                         skhd -k 'escape'

#? Unzoom all in space
resize < z             : yabai -m query --windows --space | \
                         jq -re '.[] | select(."has-fullscreen-zoom" == true) | .id' | \
                         xargs -I{} yabai -m window {} --toggle zoom-fullscreen; \
                         skhd -k 'escape'; \
                         sketchybar --trigger window_focus

#? Swap mouse window with recent
resize < s              : yabai -m window mouse --swap recent; \
                          skhd -k 'escape'


############################ Display mode ######################################

#? Focus prev display
display < 0x2F         : yabai -m display --focus prev || \
                         yabai -m display --focus next; \
                         sketchybar --trigger windows_on_spaces; \
                         skhd -k 'escape'

#? Focus next display
display < 0x2B         : yabai -m display --focus next || \
                         yabai -m display --focus prev; \
                         sketchybar --trigger windows_on_spaces; \
                         skhd -k 'escape'

#? Move window to display above
display < up           : yabai -m window --display north; \
                         yabai -m display --focus north; \
                         sketchybar --trigger windows_on_spaces; \
                         skhd -k 'escape'

#? Move window to display below
display < down         : yabai -m window --display south; \
                         yabai -m display --focus south; \
                         sketchybar --trigger windows_on_spaces; \
                         skhd -k 'escape'

#? Move window to display right
display < right        : yabai -m window --display east; \
                         yabai -m display --focus east; \
                         sketchybar --trigger windows_on_spaces; \
                         skhd -k 'escape'

#? Move window to display left
display < left         : yabai -m window --display west; \
                         yabai -m display --focus west; \
                         sketchybar --trigger windows_on_spaces; \
                         skhd -k 'escape'

#? Focus display 1-4
display < 1           : yabai -m display --focus 1; skhd -k 'escape'
display < 2           : yabai -m display --focus 2; skhd -k 'escape'
display < 3           : yabai -m display --focus 3; skhd -k 'escape'
display < 4           : yabai -m display --focus 4; skhd -k 'escape'

##################### Window mode ##############################################

#? New space + move window
window < s            : yabai -m space --create; \
                        index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')"; \
                        yabai -m window --space "${index}"; \
                        yabai -m space --focus "${index}"; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Delete current space
window < x            : index="$(yabai -m query --spaces --space | jq '.index - 1')"; \
                        yabai -m space --destroy; \
                        yabai -m space --focus "${index}"; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Minimize window
window < m            : yabai -m window --minimize; \
                        skhd -k 'escape'

# `organize` stacks windows that belong to the same app.
#? Organize windows
window < o            : ~/.config/skhd/organize "$(yabai -m query --spaces index --space | jq -r .index)"; \
                        skhd -k 'escape'

#? Restore all minimized
window < shift - m    : yabai -m query --windows | \
                        jq -re '.[] | select(."is-minimized" == true) | .id' | \
                        xargs -I{} yabai -m window --deminimize {}; \
                        skhd -k 'escape'

#? Native fullscreen
window < f            : yabai -m window --toggle native-fullscreen; skhd -k 'escape'

#? Move window to prev space
window < left         : yabai -m window --space prev; \
                        yabai -m space --focus prev; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'
#? Move window to next space
window < right        : yabai -m window --space next; \
                        yabai -m space --focus next; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Warp window west
window < h            : yabai -m window --warp west; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'
#? Warp window south
window < j            : yabai -m window --warp south; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'
#? Warp window north
window < k            : yabai -m window --warp north; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'
#? Warp window east
window < l            : yabai -m window --warp east; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Toggle bsp/stack layout
window < space        : yabai -m query --spaces --space | \
                        jq -re ".type" | \
                        xargs -I {} bash -c \
                        "if [ {} = 'stack' ]; \
                        then yabai -m space --layout bsp; \
                        else yabai -m space --layout stack; \
                        fi"; \
                        skhd -k 'escape'

#? Move window to space 1
window < 1            : yabai -m window --space  1; \
                        yabai -m space --focus 1; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 2
window < 2            : yabai -m window --space  2; \
                        yabai -m space --focus 2; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 3
window < 3            : yabai -m window --space  3; \
                        yabai -m space --focus 3; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 4
window < 4            : yabai -m window --space  4; \
                        yabai -m space --focus 4; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 5
window < 5            : yabai -m window --space  5; \
                        yabai -m space --focus 5; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 6
window < 6            : yabai -m window --space  6; \
                        yabai -m space --focus 6; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 7
window < 7            : yabai -m window --space  7; \
                        yabai -m space --focus 7; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 8
window < 8            : yabai -m window --space  8; \
                        yabai -m space --focus 8; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'

#? Move window to space 9
window < 9            : yabai -m window --space  9; \
                        yabai -m space --focus 9; \
                        sketchybar --trigger windows_on_spaces; \
                        skhd -k 'escape'
