#!/bin/bash

# Common aliases
alias ohmyzsh="code ~/.oh-my-zsh"
alias ezsh='code $FILE_DIR'
alias rzsh='source ~/.zshrc'
alias rtmux='tmux source ~/.tmux.conf'

# General purpose alias
alias tmuxls='tmux list-sessions'
tmuxattach()
{
  tmux attach-session -t "$1"
}

tmuxkillsession()
{
  tmux kill-session -t "$1"
}

alias tmuxkillall='tmux kill-server'
alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'

gitdelete()
{
  git fetch --all -p; git branch -vv | grep \": gone]\" | awk '{ print \$1 }' | xargs -n 1 git branch -D
}

alias docker='nocorrect docker'
alias dockerkillall='docker stop $(docker ps -a -q)'
alias pass='lpass show -c --password $(lpass ls  | fzf | awk \"{print $(NF)}\" | sed \"s/\]//g\")'
alias rm='rm -i'
tmuxs()
{
  tmuxinator start "$1"
}

tmuxx()
{
  tmuxinator stop "$1"
}


unalias z 2>/dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')" || exit
}

# Open bash in a docker container
dbash()
{
  docker exec -it "$1" bash
}

# Copy pwd to system clipboard by ctrl-y
function copypwd {
  pwd | pbcopy
}
zle -N copypwd
bindkey '^y' copypwd
