#!/bin/bash

# Mac OSX specific application alias.
alias studio='open -a /Applications/Android\ Studio.app'
alias rmine='open -a /Applications/RubyMine.app'
alias goland='open -a /Applications/GoLand.app'
alias bsl='brew services ls'
alias bsr='brew services restart'
alias bss='brew services start'
alias bsx='brew services stop'
alias fl='open -a ForkLift .'
alias ci='code-insiders .'

export GOPATH=$HOME/go
export GO_ENV=development

export PATH="/usr/local/opt/php@7.4/bin:$PATH"
export PATH="/usr/local/opt/php@7.4/sbin:$PATH"

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$PATH:/Applications/Sublime Text.app/Contents/SharedSupport/bin"

export PATH="/usr/local/opt/ruby@2.7/bin:$PATH"
export PATH="$PATH:$HOME/.gem/ruby/2.7.0/bin"
export PATH="$PATH:/usr/local/lib/ruby/gems/2.7.0/bin"


path+=/usr/local/bin
path+=/usr/local/mysql/bin
path+=/usr/local/sbin

function portscan()
{
  lsof -i :"$1"
}
alias portscan='portscan'

alias rsp='run_rspec'
function run_rspec()
{
  rspec ./"$1"
}

# ioreg -l -w 0 \
#     | perl -nle 'print $1 if /"kCGSSessionSecureInputPID"=(\d+)/' \
#     | uniq \
#     | xargs -I{} ps -p {} -o comm=


alias win='active-win'
alias wifi='osx-wifi-cli'
alias dm='dark-mode'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/anujchandra/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/anujchandra/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/anujchandra/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/anujchandra/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
