#!/bin/bash

if [[ "$(uname -m)" == "arm64" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

alias xbrew='arch -x86_64 /usr/local/homebrew/bin/brew'

# Compiler flags for Apple Silicon M1 Macs

libpq="$(brew --prefix libpq)"
export LDFLAGS="-L$libpq/lib"
export CPPFLAGS="-I$libpq/include"
export PATH="$libpq/bin:$PATH"
export PKG_CONFIG_PATH="$libpq/lib/pkgconfig"

libffi="$(brew --prefix libffi)"
export LDFLAGS="-L$libffi/lib"
export CPPFLAGS="-I$libffi/include"
export PKG_CONFIG_PATH="$libffi/lib/pkgconfig"

export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1) --with-arch=arm64"

llvm=$(brew --prefix llvm@11)
export LDFLAGS="-L$llvm/lib"
export CPPFLAGS="-I$llvm/include"
export PATH="$llvm/bin:$PATH"

openssl="$(brew --prefix openssl@1.1)"
export LDFLAGS="-L$openssl/lib"
export CPPFLAGS="-I$openssl/include"
export PATH="$openssl/bin:$PATH"
export PKG_CONFIG_PATH="$openssl/lib/pkgconfig"

# DELIVEROO MAC SPECIFIC FLAGS
export PATH="/usr/local/opt/v8@3.15/bin:$PATH"

# Switch Postgres version (for orderweb)
# export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/11/bin

# Mac OSX specific application alias.
alias studio='open -a /Applications/Android\ Studio.app'
alias rmine='open -a /Applications/RubyMine.app'
alias goland='open -a /Applications/GoLand.app'
alias fl='open -a ForkLift .'
alias tail_yabai='tail -f $HOMEBREW_PREFIX/var/log/yabai/*.log'
alias tail_sketchybar='tail -f $HOMEBREW_PREFIX/var/log/sketchybar/*.log'

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# shellcheck disable=SC2155
export ANDROID_SDK_ROOT="/Users/$(whoami)/Library/Android/sdk"

alias bsl='brew services ls'
alias bsr='brew services restart'
alias bss='brew services start'
alias bsx='brew services stop'

alias gbc="git branch | grep '^\*' | cut -d' ' -f2 | pbcopy"

gopath="$(go env GOPATH)"
export PATH="$PATH:$gopath/bin"

export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home

# Uninstallation command for Corretto https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/macos-install.html
# cd /Library/Java/JavaVirtualMachines/
# sudo rm -rf amazon-corretto-11.jdk

path+=/usr/local/bin

function portscan()
{
  lsof -i :"$1"
}
alias portscan='portscan'

alias rsp='run_rspec'
function run_rspec()
{
  RACK_SERVICE_TIMEOUT=0 bundle exec rspec ./"$1"
}
alias wip='git add . && git commit -m "WIP Commit"'
alias rspec='bundle exec rspec'
alias rails='bundle exec rails'
alias rake='bundle exec rake'
alias migrate='bundle exec rails db:migrate'
alias rollback='bundle exec rails db:rollback'
alias migrate_test='bundle exec rails db:migrate RAILS_ENV=test'
alias rollback_test='bundle exec rails db:rollback RAILS_ENV=test'
alias db_reset='bundle exec rails db:drop; bundle exec rails db:create'
alias cop='run_cop'

function run_cop()
{
  bundle exec rubocop ./"$1"
}

function securekb()
{
ioreg -l -w 0 \
    | perl -nle 'print $1 if /"kCGSSessionSecureInputPID"=(\d+)/' \
    | uniq \
    | xargs -I{} ps -p {} -o comm=
}

if [ -f "$(brew --prefix chruby)/share/chruby/chruby.sh" ]; then
  # shellcheck source=/dev/null
  source "$(brew --prefix chruby)/share/chruby/chruby.sh"
fi

if [ -f "$(brew --prefix chruby)/share/chruby/auto.sh" ]; then
  # shellcheck source=/dev/null
  source "$(brew --prefix chruby)/share/chruby/auto.sh"
fi

if [ -f "$(brew --prefix asdf)/libexec/asdf.sh" ]; then
  # shellcheck source=/dev/null
  source "$(brew --prefix asdf)/libexec/asdf.sh"
fi
