#!/bin/bash

## If you come from bash you might have to change your $PATH.
export GOPATH=$HOME/go
export GO_ENV=development

export PATH="/usr/local/sbin:$PATH"
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$GOBIN:$PATH"

alias win='active-win'
alias wifi='osx-wifi-cli'
alias dm='dark-mode'
