# To use this zshrc as your default zshrc file, create a symlink of this file
# in your home folder. Just create  a symlink of the zshrc file and it will
# source the other files on it's own. The command usually looks like
# ln -s ~/Personal/dotfiles/zsh/zshrc ~/.zshrc

# To profile zsh in case of slow startup, uncomment the line below and move the
# second command to the bottom of this file
# zmodload zsh/zprof
# zprof

export TERM="xterm-256color"
export EDITOR="nvim"
export LANG=en_US.UTF-8

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS

ZSH_THEME="agnoster"

plugins=(zsh-autosuggestions z zsh-syntax-highlighting zsh-completions git)

case `uname` in
  Darwin)
    export isMacOS=true
  ;;
  Linux)
    export isMacOS=false
  ;;
esac

# Check if the OS is MAC or Linux
if [ "$isMacOS" = true ]; then
  # Get the absolute path of the symlinked zshrc to read the other rc files
  ABSOLUTE_FILE_PATH="$(readlink /Users/$(whoami)/.zshrc)"
  FILE_DIR=${ABSOLUTE_FILE_PATH%??????}
  export ZSH="/Users/$(whoami)/.oh-my-zsh" # Path to your oh-my-zsh installation.
  source $(echo $FILE_DIR)/macosrc
else
  # Get the absolute path of the symlinked zshrc to read the other rc files
  ABSOLUTE_FILE_PATH="$(readlink -f /home/$(whoami)/.zshrc)"
  FILE_DIR=${ABSOLUTE_FILE_PATH%??????}
  export ZSH="/home/$(whoami)/.oh-my-zsh" # Path to your oh-my-zsh installation.
  source $(echo $FILE_DIR)/linuxrc
fi

source $(echo $FILE_DIR)/pathrc

source $ZSH/oh-my-zsh.sh

# Prevent zsh from showing the system name before each command
prompt_context () { }


# Every time compinit is invoked, it often checks its configurations and re-generates in case of change
# This only checks zcompdump if is more than 24 hours old
# autoload -Uz compinit
# if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
#   compinit
# else
#   compinit -C
# fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# ZSH completions for Alacritty
fpath+=${ZDOTDIR:-~}/.zsh_functions

source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh

# Disable that pesky auto correct
unsetopt correct_all

source $(echo $FILE_DIR)/common_aliasrc
source $(echo $FILE_DIR)/secretsrc

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi