- name: Perform Setup
  hosts: localhost
  roles:
    - role: zsh
      tags:
        - zsh
    - role: alacritty
      tags:
        - alacritty
    - role: fusuma
      tags:
        - fusuma
    - role: tmux
      tags:
        - tmux
