autocmd!
set nocompatible
set encoding=UTF-8
filetype off

set guifont=Hack_Nerd_Font:h11
set rtp+=~/.vim/bundle/Vundle.vim

" Improve vim's scrolling speed
set ttyfast
set ttyscroll=3
set lazyredraw

set tabstop=2 shiftwidth=2      " a tab is two spaces
set expandtab                   " use spaces, not tabs
set backspace=indent,eol,start  " backspace through everything in insert mode

" Searching
set hlsearch                    " highlight the search
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter
set scrolloff=0                 " keep a 5 line padding when moving the cursor
set autoindent                  " indent on enter
set smartindent                 " do smart indenting when starting a new line
set shiftround                  " indent to the closest shiftwidth
set linebreak                   " break lines at word end
set number relativenumber

" Enable yank in mac terminal
set clipboard=unnamed

" Auto-reload buffers when files are changed on disk
set autoread

augroup myvimrchooks
    au!
    autocmd bufwritepost .vimrc source ~/.vimrc
augroup END

call vundle#begin()

Plugin 'airblade/vim-gitgutter'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'fatih/vim-go'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'ryanoasis/vim-devicons'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sensible'
Plugin 'valloric/youcompleteme'
" Plugin 'vim-airline/vim-airline-themes'
" Plugin 'vim-airline/vim-airline'
Plugin 'VundleVim/Vundle.vim'
Plugin 'w0rp/ale'

call vundle#end()

syntax on
filetype plugin indent on

" Start vim with NERDTree
autocmd vimenter * NERDTree
map <C-t> :NERDTreeToggle<CR>

let mapleader = ","
map <leader>e :bufdo e!<CR>                    " reload files in buffer
map <leader>n :NERDTreeToggle<CR>              " toggle NERDTree

set laststatus=2

let g:airline_theme='base16-spacemacs'