---
- name: Install dependencies
  become: true
  apt:
    update_cache: yes
    name:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - wget
      - libbz2-dev
      - python-apt

- name: Download python
  get_url:
    url: https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz
    dest: /tmp/python.tgz
    force: yes

- name: Un-tar the package
  unarchive:
    src: /tmp/python.tgz
    dest: /tmp
    remote_src: yes

- name: Install python
  shell: |
    ./configure --enable-optimizations
    make -j 2
    sudo make altinstall
    exit 0
  args:
    chdir: /tmp/Python-3.8.5

- name: Upgrade pip
  shell: pip3.8 install -U pip
