#!/bin/sh

ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# Ctrl + Enter to launch Terminal
ctrl + shift - 0x24 : open -na /Applications/Alacritty.app
ctrl + shift - k : open -na /Applications/Forklift.app;

############################# Mode definitions ##################################
:: default   : ~/.config/skhd/mode_controller.sh default # default mode: normal
# :: active  @ : ~/.config/skhd/mode_controller.sh active # active mode: used to switch to other modes
:: display @ : ~/.config/skhd/mode_controller.sh display # display mode: focus displays, move windows to other displays
:: window  @ : ~/.config/skhd/mode_controller.sh window # window mode: manipulate windows and spaces on the current display
:: resize  @ : ~/.config/skhd/mode_controller.sh resize # resize mode: resize windows in current space
:: launch  @ : ~/.config/skhd/mode_controller.sh launch # launch mode: launch various applications

# Activate modes using the keybinding
default < ctrl + shift - d ; display
default < ctrl + shift - s ; window
default < ctrl + shift - r ; resize
default < ctrl + shift - l ; launch

# De-activate modes
display, window, resize, launch < escape ; default

display < ctrl + shift - d ; default
window < ctrl + shift - s ; default
resize < ctrl + shift - r ; default
launch < ctrl + shift - l ; default

############################# Base Keyboard shortcuts ##########################

# Switch layout of current desktop between bsp and stack
# Additionally, toggle padding for a space such that a space with
# stack layout has no padding while bsp has default paddings
# defined in yabairc
ctrl + shift - space : yabai -m query --spaces --space \
  | jq -re ".type" \
  | xargs -I {} bash -c \
  "if [ {} = 'stack' ]; \
  then yabai -m space --layout bsp; \
  else yabai -m space --layout stack; \
  fi" \
  | yabai -m space --toggle padding

# cycle applications in current space forward
ctrl + shift - right : yabai -m query --spaces --space \
                    | jq -re ".index" \
                    | xargs -I{} yabai -m query --windows --space {} \
                    | jq -sre "add \
                    | map(select(.minimized != 1)) \
                    | sort_by(.display, .frame.y, .frame.x, .id) \
                    | map(select(.title \
                    | test(\"^(?!Microsoft Teams Notification|Microsoft Teams Call in)\"))) \
                    | reverse \
                    | nth(index(map(select(.focused == 1))) - 1).id" \
                    | xargs -I{} yabai -m window --focus {}

# cycle applications in current space backward
ctrl + shift - left : yabai -m query --spaces --space \
                    | jq -re ".index" \
                    | xargs -I{} yabai -m query --windows --space {} \
                    | jq -sre "add| map(select(.minimized != 1)) \
                    | sort_by(.display, .frame.y, .frame.y, .id) \
                    | map(select(.title  \
                    | test(\"^(?!Microsoft Teams Notification|Microsoft Teams Call in)\"))) \
                    | nth(index(map(select(.focused == 1))) - 1).id" \
                    | xargs -I{} yabai -m window --focus {}

# Useful if window focus is lost
ctrl + shift - down : yabai -m window --focus mouse

# fast focus desktop
ctrl - left : yabai -m space --focus prev
ctrl - right : yabai -m space --focus next
ctrl - z : yabai -m space --focus recent
ctrl - 1 : yabai -m space --focus 1
ctrl - 2 : yabai -m space --focus 2
ctrl - 3 : yabai -m space --focus 3
ctrl - 4 : yabai -m space --focus 4
ctrl - 5 : yabai -m space --focus 5
ctrl - 6 : yabai -m space --focus 6
ctrl - 7 : yabai -m space --focus 7
ctrl - 8 : yabai -m space --focus 8
ctrl - 9 : yabai -m space --focus 9
ctrl - 0 : yabai -m space --focus 10
ctrl + alt - 1 : yabai -m space --focus 11
ctrl + alt - 2 : yabai -m space --focus 12
ctrl + alt - 3 : yabai -m space --focus 13
ctrl + alt - 4 : yabai -m space --focus 14
ctrl + alt - 5 : yabai -m space --focus 15
ctrl + alt - 6 : yabai -m space --focus 16
ctrl + alt - 7 : yabai -m space --focus 17
ctrl + alt - 8 : yabai -m space --focus 18
ctrl + alt - 9 : yabai -m space --focus 19

# Switch to space with window running in native full-screen mode
ctrl - 0x1B : yabai -m space --focus "$(yabai -m query --spaces --display | \
  jq 'map(select(."native-fullscreen" == 1))[0].index')" # - key
ctrl - 0x18 : yabai -m space --focus "$(yabai -m query --spaces --display | \
  jq 'map(select(."native-fullscreen" == 1))[1].index')" # = key

# Fast focus display
ctrl + alt - left : yabai -m display --focus prev || yabai -m display --focus next
ctrl + alt - right : yabai -m display --focus next || yabai -m display --focus prev

# float / unfloat window and center on screen
alt - t : yabai -m window --toggle float;\
          yabai -m window --grid 4:4:1:1:2:2

####################### Resize mode ############################################

# Resize focused window towards left direction
resize < h       : yabai -m window --resize left:-20:0 || yabai -m window --resize right:-20:0

# Resize focused window towards down direction
resize < j       : yabai -m window --resize bottom:0:20 || yabai -m window --resize top:0:20

# Resize focused window towards up direction
resize < k       : yabai -m window --resize top:0:-20 || yabai -m window --resize bottom:0:-20

# Resize focused window towards right direction
resize < l       : yabai -m window --resize right:20:0 || yabai -m window --resize left:20:0

# Balance all windows. Maps to `=` key
resize < 0x18    : yabai -m space --balance; skhd -k 'escape'

# Rotate tree by 90 degrees
resize < r       : yabai -m space --rotate 90

# Mirror tree y-axis
resize < y       : yabai -m space --mirror y-axis

# Mirror tree x-axis
resize < x       : yabai -m space --mirror x-axis

# Toggle window split type
resize < e       : yabai -m window --toggle split
############################ Display mode ######################################

# Focus previous display , (Like <)
display < 0x2F   : yabai -m display --focus prev || \
                   yabai -m display --focus next; \
                   skhd -k 'escape'

# Focus next display . (Like >)
display < 0x2B   : yabai -m display --focus next || \
                   yabai -m display --focus prev; \
                   skhd -k 'escape'

# Send window to next display and follow focus
display < right   : yabai -m window --display next; \
                   yabai -m display --focus next; \
                   skhd -k 'escape'

# Send window to previous display and follow focus
display < left  : yabai -m window --display prev; \
                   yabai -m display --focus prev; \
                   skhd -k 'escape'

# Focus display by number
display < 1      : yabai -m display --focus 1; skhd -k 'escape'
display < 2      : yabai -m display --focus 2; skhd -k 'escape'
display < 3      : yabai -m display --focus 3; skhd -k 'escape'
display < 4      : yabai -m display --focus 4; skhd -k 'escape'

##################### Window mode ##############################################

# create desktop and follow focus
window < c      : yabai -m space --create; \
  index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')"; \
  yabai -m space --focus "${index}"; \
  skhd -k 'escape'

# create desktop, send window to new desktop and follow focus
window < n      : yabai -m space --create; \
  index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')"; \
  yabai -m window --space "${index}"; \
  yabai -m space --focus "${index}"; \
  skhd -k 'escape'

# destroy current desktop and follow focus to previous desktop
window < x      : index="$(yabai -m query --spaces --space | jq '.index - 1')"; \
  yabai -m space --destroy; \
  yabai -m space --focus "${index}"; \
  skhd -k 'escape'

# toggle window native fullscreen
window < f       : yabai -m window --toggle native-fullscreen; skhd -k 'escape'

# send current window to i-th space and follow focus
window < left    : yabai -m window --space prev; yabai -m space --focus prev; skhd -k 'escape'
window < right   : yabai -m window --space next; yabai -m space --focus next; skhd -k 'escape'
window < 1       : yabai -m window --space 1; yabai -m space --focus 1; skhd -k 'escape'
window < 2       : yabai -m window --space 2; yabai -m space --focus 2; skhd -k 'escape'
window < 3       : yabai -m window --space 3; yabai -m space --focus 3; skhd -k 'escape'
window < 4       : yabai -m window --space 4; yabai -m space --focus 4; skhd -k 'escape'
window < 5       : yabai -m window --space 5; yabai -m space --focus 5; skhd -k 'escape'
window < 6       : yabai -m window --space 6; yabai -m space --focus 6; skhd -k 'escape'
window < 7       : yabai -m window --space 7; yabai -m space --focus 7; skhd -k 'escape'
window < 8       : yabai -m window --space 8; yabai -m space --focus 8; skhd -k 'escape'
window < 9       : yabai -m window --space 9; yabai -m space --focus 9; skhd -k 'escape'
window < 0       : yabai -m window --space 10; yabai -m space --focus 10; skhd -k 'escape'
window < alt - 1 : yabai -m window --space 11; yabai -m space --focus 11; skhd -k 'escape'
window < alt - 2 : yabai -m window --space 12; yabai -m space --focus 12; skhd -k 'escape'
window < alt - 3 : yabai -m window --space 13; yabai -m space --focus 13; skhd -k 'escape'
window < alt - 4 : yabai -m window --space 14; yabai -m space --focus 14; skhd -k 'escape'
window < alt - 5 : yabai -m window --space 15; yabai -m space --focus 15; skhd -k 'escape'
window < alt - 6 : yabai -m window --space 16; yabai -m space --focus 16; skhd -k 'escape'
window < alt - 7 : yabai -m window --space 17; yabai -m space --focus 17; skhd -k 'escape'
window < alt - 8 : yabai -m window --space 18; yabai -m space --focus 18; skhd -k 'escape'
window < alt - 9 : yabai -m window --space 19; yabai -m space --focus 19; skhd -k 'escape'
window < alt - 0 : yabai -m window --space 20; yabai -m space --focus 20; skhd -k 'escape'

##################### Launch mode ##############################################

launch < a     : open -na /Applications/Authy\ Desktop.app; skhd -k 'escape'
launch < b     : open -a "About This Mac"; skhd -k 'escape'
launch < c     : open -na /Applications/Google\ Chrome.app; skhd -k 'escape'
launch < e     : open -na /Applications/Safari.app; skhd -k 'escape'
launch < f     : open ~; skhd -k 'escape'
launch < g     : open -na /Applications/Signal.app; skhd -k 'escape'
launch < k     : open -na /Applications/Forklift.app; skhd -k 'escape'
launch < l     : open -na /Applications/Slack.app; skhd -k 'escape'
launch < m     : open -na /Applications/Spotify.app; skhd -k 'escape'
launch < r     : open -na /Applications/Rambox.app; skhd -k 'escape'
launch < s     : open "x-apple.systempreferences:"; skhd -k 'escape'
launch < t     : open -na /Applications/Microsoft\ Teams.app; skhd -k 'escape'
launch < v     : open -na /Applications/Visual\ Studio\ Code.app; skhd -k 'escape'
launch < w     : open -na /Applications/WhatsApp.app; skhd -k 'escape'

launch < d     : dark-mode; skhd -k 'escape'
launch < i     : $HOME/.config/yabai/rearrange.sh sidecar; skhd -k 'escape'
