#!/usr/bin/env sh

spacebar -m config position                     bottom
spacebar -m config height                       15
spacebar -m config spacing_left                 25
spacebar -m config spacing_right                15
spacebar -m config title                        off
spacebar -m config display                      all
spacebar -m config text_font                    "Hack Nerd Font:Bold:12.0"
spacebar -m config icon_font                    "Hack Nerd Font:Regular:12.0"
spacebar -m config background_color             0xff282828
spacebar -m config foreground_color             0xfffbf1c7

# Space Indicator
spacebar -m config space_icon_strip             1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
spacebar -m config space_icon                   

# Space Config
spacebar -m config spaces                       on
spacebar -m config space_icon_color             0xfffe8019
spacebar -m config space_icon_color_secondary   0xfffe8019
spacebar -m config space_icon_color_tertiary    0xfffe8019
spacebar -m config spaces_for_all_displays      off

# Display
spacebar -m config display_separator            off
spacebar -m config display_separator_icon       ﰴ
spacebar -m config display_separator_icon_color 0xff08bb26

# Power
spacebar -m config power                        off
spacebar -m config power_icon_color             0xffcd950c
spacebar -m config battery_icon_color           0xffd75f5f
spacebar -m config power_icon_strip              

# Clock
spacebar -m config clock                        off
spacebar -m config clock_icon                   
spacebar -m config clock_icon_color             0xffa8a8a8
spacebar -m config clock_format                 "%A, %d/%B/%y | %R"

# DND
spacebar -m config dnd_icon                     
spacebar -m config dnd_icon_color               0xffa8a8a8

spacebar -m config right_shell_command          "$HOME/.config/spacebar/get_space_info.sh"
spacebar -m config right_shell                  on

echo "spacebar configuration loaded.."
