#!/usr/bin/env sh

spacebar -m config position           bottom
spacebar -m config height             26
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config title              off
spacebar -m config display            main
spacebar -m config text_font          "Hack Nerd Font:Bold:12.0"
spacebar -m config icon_font          "Hack Nerd Font:Regular:12.0"
spacebar -m config background_color   0xff282828
spacebar -m config foreground_color   0xfffbf1c7
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip   1 2﬏ 3﬏ 4 5 6甆 7阮 8 9 10 11 12 13 14 15 16 17 18 19 20

spacebar -m config spaces             on
spacebar -m config space_icon_color   0xfffe8019
spacebar -m config space_icon_color_secondary 0xffd3869b
spacebar -m config space_icon_color_tertiary 0xff8ec07c
spacebar -m config spaces_for_all_displays on

spacebar -m config display_separator  on
spacebar -m config display_separator_icon ﰴ
spacebar -m config display_separator_icon_color 0xff08bb26


spacebar -m config clock off
spacebar -m config power off

spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%A, %d/%B/%y | %R"

# Configure right-side command
# spacebar -m config right_shell        on
# spacebar -m config right_shell_icon   

# while sleep 1 ; do spacebar -m config right_shell_command "$HOME/.config/spacebar/network_speed.sh" ; done
# spacebar -m config right_shell_command "$HOME/.config/spacebar/network_speed.sh"
# spacebar -m config right_shell_command "/Users/anujchandra/Personal/dotfiles/roles/tmux/files/network_speed.sh"

echo "spacebar configuration loaded.."
