#!/bin/sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# Follow this guide whrn updating yabai to latest version
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config mouse_drop_action            stack
yabai -m config window_shadow                float
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier                alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config external_bar                 main:0:15
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m config insert_feedback_color        0xffd65d0e

# Unmanaged apps
app_titles="(Copy|Bin|About This Mac|Info|Finder Preferences|Preferences"
app_titles+="|QuickTime Player|Stickies)"
yabai -m rule --add title="${app_titles}" manage=off

app_names="^(Calculator|Authy Desktop|Postgres|VLC|System Preferences|IINA"
app_names+="|iMazing HEIC Converter|AppCleaner|Stickies|1Password 7|VeraCrypt"
app_names+="|Tunnelblick|WireGuard|Logi Options)$"
yabai -m rule --add app="${app_names}" manage=off

# Tries to focus the window under the cursor whenever the MS teams notification gains focus
# Probably conflicts with mouse follows focus in some ways
yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    action='yabai -m window --focus next > /dev/null 2>&1'

# Don't manage WhatsApp call windows
yabai -m signal --add \
    event=window_focused \
    app='^WhatsApp$' \
    title='^$' \
    action='yabai -m window --focus next > /dev/null 2>&1'

# Focus window under cursor when an application is hidden
# yabai -m signal --add event=application_hidden \
#     action="yabai -m window --focus mouse"

# Focus window under cursor when a window is destroyed
# yabai -m signal --add event=window_destroyed \
#     action="yabai -m window --focus mouse"

# Focus window under cursor when an application is terminated
# yabai -m signal --add event=application_terminated \
#     action="yabai -m window --focus mouse"

# Rearrange windows when a new display is added
# yabai -m signal --add event=display_added \
#     action="$HOME/.config/yabai/rearrange.sh add"

# Rearrange windows when a display is removed
# yabai -m signal --add event=display_removed \
#     action="$HOME/.config/yabai/rearrange.sh remove"
