---
# REFER: https://github.com/rvm/ubuntu_rvm
- name: Install software-properties-common
  become: yes
  apt:
    name: software-properties-common

- name: Install dependencies
  become: yes
  apt:
    update_cache: yes
    name:
      - python-apt
      - python3-apt

- name: Add repository ppa:rael-gc/rvm
  become: yes
  apt_repository:
    repo: ppa:rael-gc/rvm
    state: present

- name: Install rvm
  become: yes
  apt:
    update_cache: yes
    name: rvm

- name: Print installation message
  debug:
    msg: "Installation successful. Please restart system to start using rvm."
