---
- name: Install dependencies
  become: yes
  apt:
    update_cache: yes
    name:
      - zsh
      - git

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not stat_oh_my_zsh_result.stat.exists

- name: Get zsh path
  shell: which zsh
  register: zsh_path

# ln -sf ~/Personal/dotfiles/roles/zsh/files/zshrc ~/.zshrc
- name: Copy zshrc file
  file:
    src: "{{ role_path }}/files/zshrc"
    path: "{{ lookup('env','HOME') }}/.zshrc"
    state: link
    force: yes

- name: Install oh-my-zsh plugins
  shell: |
    git clone https://github.com/changyuheng/zsh-interactive-cd.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/zsh-interactive-cd &>/dev/null
    git clone https://github.com/MichaelAquilina/zsh-you-should-use.git $ZSH_CUSTOM/plugins/you-should-use &>/dev/null
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions &>/dev/null
    git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions &>/dev/null
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting &>/dev/null
    git clone https://github.com/wfxr/forgit.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/forgit &>/dev/null

    exit 0

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ lookup('env','HOME') }}/.fzf"
    depth: 1

- name: Install fzf
  shell: "{{ lookup('env','HOME') }}/.fzf/install"

- name: Debug message
  debug:
    msg: "Please log out and login again to see changed shell"
