#!/usr/bin/env bash

set -x

# Disable animations when switching spaces
defaults write com.apple.dock expose-animation-duration -int 0

# Don't reorder Spaces based on most recent use
defaults write com.apple.dock "mru-spaces" -bool "false"

# Disable Bouncing dock icons
defaults write com.apple.dock no-bouncing -bool True

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

# Don't automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Prevent .DS_Store files from being created on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Do not span Spaces across multiple displays
defaults write com.apple.spaces spans-displays -bool false

# Disable window animations
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

# Set a fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1

# Disable automatic spelling correction
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Disable all Finder animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Do not show mounted servers on the desktop
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false

# Do not show removable media on the desktop
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Show the full POSIX path in the Finder title bar
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Do not show the status bar in Finder
defaults write com.apple.finder ShowStatusBar -bool false

# allows key-repeat in VS Code
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Enable Dock autohide
defaults write com.apple.dock autohide -bool true

killall Dock
