---
- name: Copy tmux configuration
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ lookup('env','HOME') }}/.tmux.conf"
    state: link
    force: yes

- name: Install tmux
  become: yes
  apt:
    name: tmux
    update_cache: yes

- name: Install tmux plugins
  shell: |
    if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
      git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      # Install TPM plugins.
      # TPM requires running tmux server, as soon as `tmux start-server` does not work
      # create dump __noop session in detached mode, and kill it when plugins are installed
      tmux new -d -s __noop >/dev/null 2>&1 || true
      tmux set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins"
      "$HOME"/.tmux/plugins/tpm/bin/install_plugins || true
      tmux kill-session -t __noop >/dev/null 2>&1 || true
    fi

# - name: Install tmuxinator
#   gem:
#     name: tmuxinator
#     state: latest
#
# - name: Install tmuxinator completions
#   become: yes
#   get_url:
#     url: https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh
#     dest: /usr/local/share/zsh/site-functions/_tmuxinator
