---
# ln -sf ~/Personal/dotfiles/roles/tmux/files/tmux.conf ~/.tmux.conf

- name: Copy tmux configuration
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ lookup('env','HOME') }}/.tmux.conf"
    state: link
    force: yes

- name: Install tmux(Linux)
  become: yes
  apt:
    name: tmux
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install tmux(MacOS)
  community.general.homebrew:
    name: tmux
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Install tmux plugins
  shell: |
    if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
      git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      # Install TPM plugins.
      # TPM requires running tmux server, as soon as `tmux start-server` does not work
      # create dump __noop session in detached mode, and kill it when plugins are installed
      tmux new -d -s __noop >/dev/null 2>&1 || true
      tmux set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins"
      "$HOME"/.tmux/plugins/tpm/bin/install_plugins || true
      tmux kill-session -t __noop >/dev/null 2>&1 || true
      bash $DOT_SOURCE/roles/tmux/files/override_color.sh
    fi
