#!/bin/sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Follow this guide whrn updating yabai to latest version
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur-and-monterey---automatically-load-scripting-addition-on-startup

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config mouse_drop_action            stack
yabai -m config window_shadow                float
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config external_bar                 all:0:30
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m config insert_feedback_color        0xffd65d0e

# Unmanaged apps
app_titles="(Copy|Bin|About This Mac|Info|Finder Preferences|Preferences"
app_titles+="|QuickTime Player|Stickies)"
yabai -m rule --add title="${app_titles}" manage=off

app_names="^(Calculator|Authy Desktop|Postgres|VLC|System Preferences|IINA"
app_names+="|iMazing HEIC Converter|AppCleaner|Stickies|1Password 7|VeraCrypt"
app_names+="|Tunnelblick|WireGuard|Logi Options|JetBrains Toolbox"
app_names+="|System Settings|Contexts|Contexts"
app_names+="|Logi Options\+|JetBrains Gateway|SteelSeries GG Client)$"
yabai -m rule --add app="${app_names}" manage=off

# Tries to focus the window under the cursor whenever the MS teams notification gains focus
# Probably conflicts with mouse follows focus in some ways
yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    action='yabai -m window --focus next > /dev/null 2>&1'

# Don't manage WhatsApp call windows
yabai -m signal --add \
    event=window_focused \
    app='^WhatsApp$' \
    title='^$' \
    action='yabai -m window --focus next > /dev/null 2>&1'

yabai -m signal --add label=space_changed event=space_changed \
    action="$HOME/.config/yabai/save_recent_space.sh"

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=space_changed action="sketchybar --trigger windows_on_spaces"

yabai -m signal --add label=stack_same_name_applications event=window_created \
    action="$HOME/.config/yabai/stack_same_name_applications.sh"

echo "yabai configuration loaded.."
