#!/usr/bin/env zsh

function ruby_config_arm() {
	local openssl3="$HOMEBREW_PREFIX/opt/openssl"
	export PATH="$openssl3/bin:$PATH"
	RUBY_CONFIGURE_OPTS="--with-openssl-dir=$openssl3"
	export RUBY_CONFIGURE_OPTS
	export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
}

if [[ "$CPUTYPE" == "arm64" ]] || [[ -d "/opt/homebrew" ]]; then
	# Apple Silicon
	eval "$(/opt/homebrew/bin/brew shellenv)"
	ruby_config_arm
	# Dir to store manual arm binaries
	export PATH="$PATH:$HOME/.local/bin"
else
	# MacOS on Intel (default homebrew location)
	export PATH="$PATH:$HOME/.local/bin"
fi

# Mac OSX specific application alias.
alias studio='open -a /Applications/Android\ Studio.app'
alias rmine='open -a /Applications/RubyMine.app'
alias c='code .'
alias cc='cursor .'
alias ss='surf .'
alias fl='open -a ForkLift .'
alias tail_yabai='tail -f $HOMEBREW_PREFIX/var/log/yabai/*.log'
alias tail_sketchybar='tail -f $HOMEBREW_PREFIX/var/log/sketchybar/*.log'

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$PATH:/Users/anujchandra/.codeium/windsurf/bin"

# shellcheck disable=SC2155
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export THOR_MERGE="surf -d $1 $2"

alias bri='brew install'
alias bru='brew uninstall'
alias bsl='brew services ls'
alias bsr='brew services restart'
alias bss='brew services start'
alias bsx='brew services stop'
alias tf='terraform'
alias gbc="git branch | grep '^\*' | cut -d' ' -f2 | pbcopy"

path+=/usr/local/bin

function portscan() {
	lsof -i :"$1"
}

function rsp() {
	local spec_file
	spec_file="$(echo "$1" | sed 's/^spec\///')"
	RACK_SERVICE_TIMEOUT=0 bundle exec rspec ./spec/"$spec_file"
}

alias wip='git add . && git commit -m "WIP Commit"'

function wip_unset() {
	local msg
	msg="$(git log -1 --pretty=%B)"
	if [ "$msg" = "WIP Commit" ]; then
		git reset HEAD~1
	else
		echo "No WIP commit found. Check your git log"
		return 1
	fi
}

alias b='bundle'
alias bi='bundle install'
alias ba='bundle add'
alias bu='bundle update'

function rails() {
	if [ -e "Gemfile" ]; then
		bundle exec rails "$@"
	else
		command rails "$@"
	fi
}

function rspec() {
	if [ -e "Gemfile" ]; then
		bundle exec rspec "$@"
	else
		command rspec "$@"
	fi
}

alias migrate='STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 rails db:migrate'
alias rollback='STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 rails db:rollback'
alias migrate_test='STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 bundle exec rails db:migrate RAILS_ENV=test'
alias rollback_test='STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 bundle exec rails db:rollback RAILS_ENV=test'
function db_reset() {
	set +x
	STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 bundle exec rails db:drop
	STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 bundle exec rails db:create
	STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 bundle exec rails db:migrate

	STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 RAILS_ENV="test" bundle exec rails db:drop
	STATEMENT_TIMEOUT=0 DATABASE_STATEMENT_TIMEOUT=0 RAILS_ENV="test" bundle exec rails db:create
	STATEMENT_TIMEOUT=0 RAILS_ENV="test" bundle exec rails db:migrate
}

function securekb() {
	ioreg -l -w 0 |
		perl -nle 'print $1 if /"kCGSSessionSecureInputPID"=(\d+)/' |
		uniq |
		xargs -I{} ps -p {} -o comm=
}

# For newer versions of asdf >=0.16
if [ -d "$HOME/.asdf" ]; then
  # shellcheck source=/dev/null
  [ -f ~/.asdf/plugins/golang/set-env.zsh ] && . ~/.asdf/plugins/golang/set-env.zsh
  # shellcheck source=/dev/null
	[ -f ~/.asdf/plugins/java/set-java-home.zsh ] && . ~/.asdf/plugins/java/set-java-home.zsh

	export ASDF_DATA_DIR="$HOME/.asdf"
	export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
	export ASDF_GOLANG_MOD_VERSION_ENABLED=true
fi

function suyabai() {
	local sha256
	sha256=$(shasum -a 256 "$(which yabai)" | awk "{print \$1;}")
	if [ -f "/private/etc/sudoers.d/yabai" ]; then
		sudo sed -i '' -e 's/sha256:[[:alnum:]]*/sha256:'"${sha256}"'/' /private/etc/sudoers.d/yabai
	else
		echo "sudoers file does not exist yet. creating one now"
		echo "$USER ALL=(root) NOPASSWD: sha256:${sha256} $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
	fi
}

function presentation-mode() {
	if [[ -f "$HOME/Personal/scripts/scripts/presentation_mode/terminal.sh" ]]; then
		"$HOME/Personal/scripts/scripts/presentation_mode/terminal.sh"
	fi

	if [[ -f "$HOME/Personal/scripts/scripts/presentation_mode/editor.sh" ]]; then
		"$HOME/Personal/scripts/scripts/presentation_mode/editor.sh"
	fi
}
