export TERM="xterm-256color"
ABSOLUTE_FILE_PATH="$(readlink -f /home/$(whoami)/.zshrc)"
FILE_DIR=${ABSOLUTE_FILE_PATH%??????}

source $(echo $FILE_DIR)/pathrc

# Path to your oh-my-zsh installation.
export ZSH="/home/$(whoami)/.oh-my-zsh"

ZSH_THEME="powerlevel9k/powerlevel9k"
source $(echo $FILE_DIR)/powerlevel9krc

ENABLE_CORRECTION="true"

plugins=(git zsh-autosuggestions z zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Check if the OS is MAC or Linux
sw_vers -productName 2> /dev/null && source $(echo $FILE_DIR)/macosrc || source $(echo $FILE_DIR)/linuxrc

export LANG=en_US.UTF-8

BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Prevent zsh from showing the system name before each command
prompt_context () { }

source $(echo $FILE_DIR)/common_aliasrc

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
