---
- name: Install dependencies
  become: true
  apt:
    update_cache: yes
    name:
      - python-apt
      - python3-apt
  when: ansible_distribution == 'MacOSX'

- name: Add repository ppa:mmstick76/alacritty
  become: yes
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Install alacritty
  become: yes
  apt:
    name: alacritty
    update_cache: yes
    force: yes
  when: ansible_distribution == 'MacOSX'

- name: Create config directory
  file:
    path: "{{ lookup('env','HOME') }}/.config/alacritty"
    state: directory

- name: Copy config file(Linux)
  file:
    src: "{{ role_path }}/files/alacritty_linux.yml"
    dest: "{{ lookup('env','HOME') }}/.config/alacritty/alacritty.yml"
    state: link
    force: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# ln -sf ~/Personal/dotfiles/roles/alacritty/files/alacritty_mac.toml ~/.config/alacritty/alacritty.toml
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
- name: Copy config file(Mac)
  file:
    src: "{{ role_path }}/files/alacritty_mac.yml"
    dest: "{{ lookup('env','HOME') }}/.config/alacritty/alacritty.yml"
    state: link
    force: yes
  when: ansible_distribution == 'MacOSX'
