# git clone https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
# unzip Hack.zip -d ~/.fonts
# fc-cache -fv
# rm -rf Hack.zip
# TODO: Setup a playbook to install nerd font on a MacOS

---
- name: Download Hack Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: /tmp/Hack.zip

- name: Create fonts directory
  file:
    path: "{{ lookup('env','HOME') }}/.fonts"
    state: directory

- name: Unzip font
  unarchive:
    src: /tmp/Hack.zip
    dest: "{{ lookup('env','HOME') }}/.fonts"
    remote_src: yes

- name: Rebuild fonts cache
  shell: fc-cache -fv

- name: Print debug message
  debug:
    msg: "Please restart the system to use the installed fonts"
